language: ruby
cache: bundler
rvm:
  - 2.7.2
services:
  - postgresql
  - redis-server
node_js:
  - 12
before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - bash script/travis_elasticsearch_upgrade.sh
  - sleep 10
  - bin/yarn
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails webpacker:compile
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT