development: &default
  autocomplete:
    separator: '{'
    terminator: ',,'
  bookmarks:
    notes_max: 5000
  chapters:
    content_min: 10
    content_max: 510000
  collections:
    name_max: 255
    title_max: 255
  host: 'localhost:3000'
  items_per_page: 20
  jwt_secret: 'override_me_locally'
  locales:
    default_id: 1
  mail:
    sender: 'nobody@example.com'
  media:
    blacklisted_srcs: []
  profiles:
    title_max: 255
    location_max: 255
    about_me_max: 2000
  pseuds:
    name_min: 1
    name_max: 40
    description_max: 500
  redis:
    url: 'redis://localhost:6379'
  search:
    bookmark_shards: 5
    max_results: 100000
    prefix: 'ao3api'
    pseud_shards: 1
    tag_shards: 1
    tags_per_page: 50
    url: 'http://127.0.0.1:9400'
    work_shards: 5
  series:
    notes_max: 5000
    summary_max: 1250
    title_max: 255
  tags:
    name_min: 1
    name_max: 100
  users:
    login_min: 3
    login_max: 40
    password_min: 6
    password_max: 40
  works:
    title_min: 1
    title_max: 255
    summary_max: 1250
    notes_max: 5000

test:
  <<: *default
sandbox:
  <<: *default
  host: 'https://otw-elz.herokuapp.com'
  mail:
    sender: 'otw@otw-elz.herokuapp.com'
  redis:
    url: <%= ENV['REDIS_URL'] %>
  search:
    url: <%= ENV['BONSAI_URL'] %>
