defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ao3
  password: ao3dev

development:
  <<: *defaults
  database: ao3_api_development

test:
  <<: *defaults
  database: ao3_api_test

production:
  <<: *defaults
  database: ao3_api_production
  password: <%= ENV['AO3_API_DATABASE_PASSWORD'] %>

sandbox:
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>
